apiVersion: v1
kind: Service
metadata:
  name: api-cluster-ip-service-%pullRequest%
spec:
  type: NodePort
  selector:
    component: api-%pullRequest%
  ports:
    -   protocol: TCP
        port: 3001
        targetPort: 3001
