name: Node.js CI

on:
  push:

jobs:
  build:
    timeout-minutes: 10
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: bash build.sh $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
